### ISSUE TITLE
External media example with ads

### ISSUE THREAD

**Issue by Mukesh87182** [flowplayer/apple-sdk-releases#21]
Can you please let me know, How I can add adschedule parameter and its value through MediaExternal?

MediaExternal(
        url: .init(string: "https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8"
        )!
      

Please share examples for MediaExternal with adsechdule parameter and its value. 

Thanks

**Comment by rashadatjou** [comment]
You can initialize `MediaExternal` with an `AdSchedule` using the following `init`:

```
  public init(
    url: URL,
    adSchedule: AdSchedule? = nil,
    preferredPeakBitRate: Double? = nil
  ) {
    self.url = url
    self.adSchedule = adSchedule
    self.preferredPeakBitRate = preferredPeakBitRate
  }
  ```
  
  The `AdSchedule` protocol has two implementations: 
  1. `AdScheduleWaterfall`
  2. `AdScheduleRemote`
  
  To learn more about which one to use pleas visit our docs here: 
  https://developer.wowza.com/docs/wowza-flowplayer/apple-sdk/ios-features/advertisements/

**Comment by Mukesh87182** [comment]
![Screenshot 2023-12-19 at 11 33 23 AM](https://github.com/flowplayer/apple-sdk-releases/assets/53814343/5a038a66-b3ea-4a31-8ec6-5f605b9c7b1c)
