### ISSUE TITLE
unable to add the AdSchedule protocols 

### ISSUE THREAD

**Issue by Mukesh87182** [flowplayer/apple-sdk-releases#22]
![Screenshot 2023-12-19 at 11 50 57 AM](https://github.com/flowplayer/apple-sdk-releases/assets/53814343/30eb47e5-8a75-49cb-b96b-0125a5b22446)
![Screenshot 2023-12-19 at 11 33 23 AM](https://github.com/flowplayer/apple-sdk-releases/assets/53814343/52f2608f-22fc-4785-ae7e-cd4da81449a2)

I am unable to add the AdSchedule protocols "AdScheduleRemote" and "AdScheduleWaterfall". It gives me the error "'AdScheduleRemote' and 'AdScheduleWaterfall' cannot be constructed because it has no accessible initializers".  Please let me know how I can initialize this.
 I follow the following link:https://developer.wowza.com/docs/wowza-flowplayer/apple-sdk/ios-features/advertisements/

Please share example how i can add this

Thanks

_Originally posted by @Mukesh87182 in https://github.com/flowplayer/apple-sdk-releases/issues/21#issuecomment-1862179660_

**Comment by rashadatjou** [comment]
Hey @Mukesh87182 thank you for reporting this bug. We have scheduled a planned release tomorrow and will add this fix into it. Sorry for the inconvenience.

mehdi[dot]rashadatjou@wowza.com

**Comment by rashadatjou** [comment]
@Mukesh87182 FlowplayerSDK `4.5.0` with the fix please test it and we hope that it will resolve your issue
