### ISSUE TITLE
An error occurred while displaying the advertisement

### ISSUE THREAD

**Issue by Mukesh87182** [flowplayer/apple-sdk-releases#24]
![image](https://github.com/flowplayer/apple-sdk-releases/assets/53814343/f53528d2-7697-4c0f-aec0-40b7108e8f48)

Ad failed with error: An error occurred while displaying the advertisement.
----
⛔️ ERROR [21-12-2023 13:19:053] AdService.swift > ima(_:didFailWith:) > 226:17
An error occurred while displaying the advertisement.

After adding the AdScheduleWaterfall protocol, when I play the video the advertisement does not display it gives me an Ad failed with error: An error occurred while displaying the advertisement. I have attached the screenshot for the same. Please check and let me know how I can display the ad in video using the AdScheduleWaterfall protocol.

The ads working fine on AdscheduleRemote 
Protocol.

Thanks

**Comment by rashadatjou** [comment]
@Mukesh87182 thank you for the feedback. Will fix this and get back to you ho ho ho 🎅

**Comment by rashadatjou** [comment]
@Mukesh87182 I have tested out the `AdScheduleWaterfall` and it works. The Google IMA SDK is really sensitive with what type of `AdBreak` URLs you use for each ad-break. Make sure that all URLs that you provided above are valid and work.

**Comment by rashadatjou** [comment]
I will push out an example demonstrating the `AdScheduleWaterfall`

**Comment by rashadatjou** [comment]
I have added examples for both iOS and tvOS using the `AdScheduleWaterfall` please test them out and get back to me. I would advice you to try to remove the AdBreak one by one in your example and see which one is faulty.

**Comment by Mukesh87182** [comment]
Ok, I will check example on Tuesday as I have a weekend and also holiday on
Monday due to Christmas.

I will update you after checked the example.

Thanks.

**Comment by Mukesh87182** [comment]
@rashadatjou  I have checked the example for AdScheduleWaterfall and found that the ad URL which you have added/provided in the example is working fine but our ad URL is not loading in AdScheduleWaterfall protocol. They still give us the error
"⛔️ ERROR [26-12-2023 13:03:024] AdService.swift > ima(_:didFailWith:) > 226:17
An error occurred while displaying the advertisement."

The ad URL which I have used is working fine in the AdScheduleRemote protocol in the case of the AdScheduleWaterfall protocol they give us an error.  I have attached the screenshot for the same. Please check it and let me know how I can use the ad URL in AdScheduleWaterfall.

Thanks.

![image](https://github.com/flowplayer/apple-sdk-releases/assets/53814343/c54eae35-8b8d-4c78-9866-baf81fd473b3)

**Comment by Mukesh87182** [comment]
@rashadatjou  Also, can you please let me know how I can use all values of the AdScheduleWaterfall protocol (preAdBreak,midAdBreak,postAdBreak) at the same time because I found that only one value of AdScheduleWaterfall can execute on the same time. Please check it and let me know how I can use all values at the same time.  

![image](https://github.com/flowplayer/apple-sdk-releases/assets/53814343/4d9fe239-8dc5-4247-9fc7-a1525ce5a56f)

In the screenshot, I have added the values of preAdBreak and midAdBreak. The preAdBreak is played before the media content which is working fine but the midAdBreak ad started after 10 seconds. It gives me the same error.

Thanks

**Comment by rashadatjou** [comment]
@Mukesh87182 Thank you for the detailed reply. I will do my best to get back to you with the issue that is currently affecting you. I also noticed the logs are to vague and do not portrait the issue that triggered them. Will update the logging as well so that you are more informed about the errors.

**Comment by Mukesh87182** [comment]
Ok, thank you.

**Comment by Mukesh87182** [comment]
Hi @rashadatjou 

Any update regarding the above issue?

**Comment by rashadatjou** [comment]
@Mukesh87182 happy holidays! Our whole team is on vacation this week. We will make this our top priority when we get back next week.

**Comment by Mukesh87182** [comment]
Ok, Thanks for the updates.

**Comment by rashadatjou** [comment]
@Mukesh87182 hope you are doing well. To better help you with the issue you are facing please provide me with the following a url sample of the ads you are trying to show and your Flowplayer or Wowza customer ID so that I can accurately test out what is causing this issue with your setup. Here is my email mehdi.rashadatjou@wowza.com please send it there as these are sensitive informations.

**Comment by rashadatjou** [comment]
@Mukesh87182 a new version of the SDK is out `4.6.0` which adds support for better logging for the ads.

**Comment by rashadatjou** [comment]
I will close this issue for now as it was resolved by using `AdScheduleRemote` instead of `AdScheduleWaterfall` in your case.

**Comment by Mukesh87182** [comment]
HI @rashadatjou 

I have checked your latest SDK and sample but they don't contain SDK version 4.6.0. Even the latest sample contains SDK version 4.5.0. I tried to update my pods with and without specifying the version but it does not work and gives me an error. Please check again, if you have updated the SDK correctly.
![Screenshot 2024-01-18 at 12 39 23 PM](https://github.com/flowplayer/apple-sdk-releases/assets/53814343/fc09429a-4b3a-49bf-bc49-3695e8154924)

![image](https://github.com/flowplayer/apple-sdk-releases/assets/53814343/79db85cb-0aad-474f-aebe-85b0ddcd882c)
