### ISSUE TITLE
FlowPlayerSDK 4.6.0 (Pod installation issue)

### ISSUE THREAD

**Issue by Mukesh87182** [flowplayer/apple-sdk-releases#25]
HI @rashadatjou

I have checked your latest SDK and sample but they don't contain SDK version 4.6.0. Even the latest sample contains SDK version 4.5.0. I tried to update my pods with and without specifying the version but it does not work and gives me an error. Please check again, if you have updated the SDK correctly.

![image](https://github.com/flowplayer/apple-sdk-releases/assets/53814343/32a59b55-3b98-49d0-a314-8c8a76062bcb)
![image](https://github.com/flowplayer/apple-sdk-releases/assets/53814343/df4772fc-a278-4b09-b534-626b82b19a3f)

**Comment by rashadatjou** [comment]
@Mukesh87182 just released version `4.6.0` of the SDK for CocoaPods please try again.

**Comment by rashadatjou** [comment]
If it is still not available please check in 30 minutes as CocoaPods takes a while to update it's main trunk
