### ISSUE TITLE
How to stop FlowPlayerView in background mode

### ISSUE THREAD

**Issue by Mukesh87182** [flowplayer/apple-sdk-releases#26]
@rashadatjou 

Please let me know how I can close/stop the flow player view in the background mode. I have faced an issue when I close the flow player view the ads and video are played in background mode even If I have closed the flow player view.

Please share any examples with me.

Thanks

**Comment by rashadatjou** [comment]
@Mukesh87182 regarding background playback here is the docs for it https://developer.wowza.com/docs/wowza-flowplayer/apple-sdk/ios-features/background-playback/#enable-background-playback. 

If you do not want the player to continue playing in the background make sure to disable the `enableBackgroundPlayback ` property and also please look at the example in the link above as it will explain you everything that you need to know.

**Comment by Mukesh87182** [comment]
@rashadatjou 
The enableBackgroundPlayback property is already implemented. The issue is that if I want to remove the player from the memory and reinitialized it. However, removing it from the memory causes an issue. I tried player.stop() and deinit() both did not work for me.

**Comment by rashadatjou** [comment]
Can you send me screen-recording of what is exactly happening?

**Comment by Mukesh87182** [comment]
Hi @rashadatjou 

I have shared the video with you. You can find the following videos in the link

https://drive.google.com/file/d/1FydV0KYAOgHQ9oAP-_XsbJ4WYsmyP5g0/view?usp=sharing

1) In the first video when the ad appears on the screen. When I close the player then the ad and the video now running in the background.
![image](https://github.com/flowplayer/apple-sdk-releases/assets/53814343/7a070b7b-adc8-4e9b-b9b8-cd28b5a4f631)

2)In the second video when there is no ad appear on the video. The video is not running in the background which is fine.
I have shared the video in that case

https://drive.google.com/file/d/1wU7ocXLD4X2GetrrQqu_I9b2VLPDSvEJ/view?usp=sharing

I have used the following code in that case. Please check the screenshot

![image](https://github.com/flowplayer/apple-sdk-releases/assets/53814343/8e70533d-8558-4451-a5e4-07be1366fb98)

My issue is that when the ad appears on the video and I need to close the player the video/ad is not closed. They are running in the background. Please check and share your thoughts with me.

Thanks

**Comment by rashadatjou** [comment]
@Mukesh87182 the main problem here is that player keeps playing even though you have explicitly told it to stop. I think what is causing the issue is that the `player.state != .play` that is why the code never get's triggered. Can you verify what the state of the player is when the `cleanUpPlayerForReuse()` is called?

**Comment by rashadatjou** [comment]
> @Mukesh87182 the main problem here is that player keeps playing even though you have explicitly told it to stop. I think what is causing the issue is that the `player.state != .play` that is why the code never get's triggered. Can you verify what the state of the player is when the `cleanUpPlayerForReuse()` is called?

When the ads are playing the player is not in playing state. You can use the `playbackState` which is the state of what is playing currently in the player and check that. `playbackState == .ads` that means the player has not started yet.

**Comment by rashadatjou** [comment]
> > @Mukesh87182 the main problem here is that player keeps playing even though you have explicitly told it to stop. I think what is causing the issue is that the `player.state != .play` that is why the code never get's triggered. Can you verify what the state of the player is when the `cleanUpPlayerForReuse()` is called?
> 
> When the ads are playing the player is not in playing state. You can use the `playbackState` which is the state of what is playing currently in the player and check that. `playbackState == .ads` that means the player has not started yet.

I think the best thing here is to remove any checks in the method (remove the `player.state == .play`) and just stop the player.

**Comment by Mukesh87182** [comment]
Hi @rashadatjou 



> > > @Mukesh87182 the main problem here is that player keeps playing even though you have explicitly told it to stop. I think what is causing the issue is that the `player.state != .play` that is why the code never get's triggered. Can you verify what the state of the player is when the `cleanUpPlayerForReuse()` is called?
> > 
> > 
> > When the ads are playing the player is not in playing state. You can use the `playbackState` which is the state of what is playing currently in the player and check that. `playbackState == .ads` that means the player has not started yet.
> 
> I think the best thing here is to remove any checks in the method (remove the `player.state == .play`) and just stop the player.



I have removed the checks in the method (remove the `player.state == .play`) and just stopped the player and it worked. But the problem is that when we play the video next time, then the player controls are not visible in the player like ( play/pause and forward/backward buttons)

I have shared the video link. Please check it and let me know your thoughts. Also, I have attached the code screenshot

![Screenshot 2024-01-24 at 9 56 38 AM](https://github.com/flowplayer/apple-sdk-releases/assets/53814343/e669ca4f-e4a8-4421-b883-fc8a448df43c)


https://drive.google.com/file/d/1oTCZdQY4iiycXoubpjcychLnLHHkZlWq/view?usp=sharing

**Comment by gunveerintellinez** [comment]
@rashadatjou could you please update this?

**Comment by vijaykansala** [comment]
@rashadatjou  could you please update on this ticket?

**Comment by rashadatjou** [comment]
Closing this issue as it became stale.
