### ISSUE TITLE
Videos are not loading

### ISSUE THREAD

**Issue by Vikalp00** [flowplayer/apple-sdk-releases#27]
Videos are loading in the sample application after adding access token.

**Comment by rashadatjou** [comment]
@Vikalp00 thanks for the feedback. We make sure to test out the Apple SDK rigorously before each release to make sure that it meets the highest criteria for quality. 

The issue you are experiencing is tide with the `accessToken` you are using to initialize the SDK and not the SDK itself. Please contact support to provide you with a valid `accessToken` to actually load the media items from our services.
